# Generated by Selenium IDE
import pytest, unittest, mock, module
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

'''
社会治安综合治理信息系统
selenium登录系统后保存cookie
'''


class Zan(unittest.TestCase):
    def setUp(self):
        self.vars = {}
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://thweb.weixinzsb.net:8000"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_zan(self):
        self.driver.get("http://thweb.weixinzsb.net:8000")
        self.driver.set_window_size(800, 1000)
        time.sleep(1.1)
        vercode = input('请手动输入验证码:')
        self.driver.find_element(By.ID, "UserName").send_keys("13503872669")
        self.driver.find_element(By.ID, "Password").send_keys('872669')
        self.driver.find_element(By.ID, "VerificationCode").click()
        self.driver.find_element(By.ID, "VerificationCode").send_keys(vercode)
        self.driver.find_element(By.ID, "btn_OK").click()
        self.driver.find_element_by_xpath('//*[@id="textC"]').click()
        # time.sleep(5)
        # self.driver.find_element(By.ID, "btn_AddClick").click()
        time.sleep(2)
        cookies = self.driver.get_cookies()
        with open("../../jiucai/cookies_zan.txt", "w") as fp:
            json.dump(cookies, fp)
        time.sleep(5)

    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)


if __name__ == '__main__':
    pytest.main(['-s', 'get_cookie_1.py'])
